<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-android</TargetFramework>
		<RuntimeIdentifier>android-arm64</RuntimeIdentifier>

		<!--Material 材料-->
		<UseMaterial3>true</UseMaterial3>
		
		<!-- MAUI -->
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<OutputType>Exe</OutputType>

		<RootNamespace>Haiyu.Mobile</RootNamespace>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		

		<!-- NativeAOT -->
		<IsAotCompatible>true</IsAotCompatible>

		<!-- Debug 不执行 NativeAOT -->
		<PublishAot Condition="'$(Configuration)'=='Debug'">false</PublishAot>

		<!-- Release 执行 NativeAOT -->
		<PublishAot Condition="'$(Configuration)'=='Release'">true</PublishAot>

		<!-- Trim -->
		<PublishTrimmed>true</PublishTrimmed>

		<EnableAotAnalyzer>true</EnableAotAnalyzer>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>


		<!-- Android -->
		<AndroidPackageFormat>apk</AndroidPackageFormat>


		<!-- XAML Source Generator -->
		<MauiXamlInflator>SourceGen</MauiXamlInflator>


		<!-- App Info -->
		<ApplicationTitle>Haiyu.Mobile</ApplicationTitle>

		<ApplicationId>com.companyname.haiyu.mobile</ApplicationId>

		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>
		<!--Zip Align-->
		<AndroidUseApkSigner>true</AndroidUseApkSigner>
		<AndroidZipAlign>true</AndroidZipAlign>

		<!-- Android minimum -->
		<SupportedOSPlatformVersion>21.0</SupportedOSPlatformVersion>


		<!-- Only ARM64 -->
		<Platforms>ARM64</Platforms>

	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">

		<PublishAot>false</PublishAot>

		<PublishTrimmed>false</PublishTrimmed>

	</PropertyGroup>
	
	<ItemGroup>

		<!-- Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />


		<!-- Splash -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />


		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />

		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />


		<!-- Fonts -->
		<MauiFont Include="Resources\Fonts\*" />


		<!-- Raw -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />

	</ItemGroup>



	<ItemGroup>

		<PackageReference Include="CommunityToolkit.Maui" Version="15.0.0" />

		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />

		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.90" />


		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.10" />


		<PackageReference Include="ZXing.Net.Maui.Controls" Version="0.10.3" />

	</ItemGroup>



	<ItemGroup>
	  <Compile Update="Views\Popups\LoginGeetPopup.xaml.cs">
	    <DependentUpon>LoginGeetPopup.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>


	<ItemGroup>
	  <MauiXaml Update="Views\AddKuroUserPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Popups\LoginGeetPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SettingPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\UserManagerPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>


	<ItemGroup>
	  <Folder Include="Services\" />
	</ItemGroup>


</Project>