<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <PublishAot>true</PublishAot>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.2.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ABI\ABI.Models\ABI.Models.csproj" />
    <ProjectReference Include="..\ABI\ABIRuntime\ABIRuntime.csproj" />
  </ItemGroup>

</Project>
